import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function setup(){const elements=new Map();const make=()=>({focus(){},hidden:false,disabled:false,textContent:'',style:{},classList:{remove(){}},querySelector(){return this},getContext(){return new Proxy({}, {get:()=>()=>{}})}});const document={getElementById(id){if(!elements.has(id))elements.set(id,make());return elements.get(id)},querySelectorAll(){return []},addEventListener(){}};const c=vm.createContext({document,Image:class{},requestAnimationFrame(){},addEventListener(){},localStorage:{setItem(){}}});vm.runInContext(readFileSync(new URL('../public/berry-beef.js',import.meta.url),'utf8'),c);return s=>vm.runInContext(s,c)}
test('Berry Beef jumps, lands on platforms, and clears input on pause',()=>{const run=setup();run('begin(); hero.x=220; press("jump"); for(let i=0;i<55;i++)step(.016)');assert.equal(run('hero.y'),405);run('press("right");pause()');assert.equal(run('keys.size'),0);assert.equal(run('phase'),'paused')});
test('rival guards attacks, becomes vulnerable after stomp, and progresses rounds',()=>{const run=setup();run('begin(); hero.x=750; rival.x=800; press("hit"); step(.01)');assert.equal(run('rival.hp'),5);run('attack=0;rival.mode="recover";rival.timer=0;press("hit");step(.01)');assert.equal(run('rival.hp'),4);run('rival.hp=1;attack=0;press("hit");hero.x=rival.x-40;step(.01)');assert.equal(run('phase'),'menu');run('document.getElementById("next").onclick()');assert.equal(run('level'),1);assert.equal(run('hero.hp'),5)});
test('damage has invulnerability and retries the current round without campaign storage',()=>{const run=setup();run('level=2;begin();hurt();hurt()');assert.equal(run('hero.hp'),4);run('hero.hp=1;inv=0;hurt()');assert.equal(run('phase'),'menu');run('document.getElementById("next").onclick()');assert.equal(run('level'),2);assert.equal(run('hero.hp'),5)});

test('stomp has a warning, locked landing target, and recovery only after landing',()=>{const run=setup();run('begin();rival.timer=2.1;step(.01)');assert.equal(run('rival.mode'),'warn');const target=run('rival.target');run('hero.x=400;rival.timer=.71;step(.01)');assert.equal(run('rival.mode'),'air');assert.equal(run('rival.target'),target);run('for(let i=0;i<60;i++)step(.016)');assert.equal(run('rival.mode'),'recover');assert.equal(run('rival.y'),520)});
test('phone portrait and landscape keep the floor above touch controls',()=>{const run=setup();for(const [w,h]of [[393,852],[852,393],[320,568],[1280,720]]){run(`var vp=viewport(${w},${h})`);const floorY=run('vp.offset+520*vp.scale');assert.ok(floorY<=h-run('vp.bottom')+.01);assert.ok(floorY>=run('vp.top')+70)}});
test('held attack repeats and the third-round victory reaches a real ending',()=>{const run=setup();run("level=2;begin();rival.mode='recover';rival.timer=0;hero.x=rival.x-40;rival.hp=2;press('hit');step(.01);hero.x=rival.x-40;for(let i=0;i<22;i++)step(.016)");assert.equal(run('phase'),'menu');assert.equal(run('rival.hp'),0)});
